import type { ClassDefinition } from "./types";

const KNOWLEDGE_ALL = [
  "knowledgeArcana",
  "knowledgeDungeoneering",
  "knowledgeEngineering",
  "knowledgeGeography",
  "knowledgeHistory",
  "knowledgeLocal",
  "knowledgeNature",
  "knowledgeNobility",
  "knowledgePlanes",
  "knowledgeReligion",
];

/** The 11 base classes (Core Rulebook, Open Game Content). Class features are named
 * milestones, not a full mechanical simulation (e.g. rage powers, rogue talents, bloodline
 * powers are chosen freely by the player and just noted in free text on the sheet). */
export const CLASSES: ClassDefinition[] = [
  {
    id: "barbarian",
    nameKey: "srd:class.barbarian",
    hitDie: 12,
    babProgression: "full",
    saveProgressions: { fort: "good", ref: "poor", will: "poor" },
    skillPointsPerLevel: 4,
    classSkillIds: [
      "acrobatics",
      "climb",
      "craft",
      "handleAnimal",
      "intimidate",
      "knowledgeNature",
      "perception",
      "ride",
      "survival",
      "swim",
    ],
    isSpellcaster: false,
    features: [
      { level: 1, nameKey: "srd:classFeature.barbarian.fastMovement" },
      { level: 1, nameKey: "srd:classFeature.barbarian.rage" },
      { level: 2, nameKey: "srd:classFeature.barbarian.ragePower" },
      { level: 2, nameKey: "srd:classFeature.barbarian.uncannyDodge" },
      { level: 3, nameKey: "srd:classFeature.barbarian.trapSense" },
      { level: 5, nameKey: "srd:classFeature.barbarian.improvedUncannyDodge" },
      { level: 7, nameKey: "srd:classFeature.barbarian.damageReduction" },
      { level: 11, nameKey: "srd:classFeature.barbarian.greaterRage" },
      { level: 17, nameKey: "srd:classFeature.barbarian.tirelessRage" },
      { level: 20, nameKey: "srd:classFeature.barbarian.mightyRage" },
    ],
  },
  {
    id: "bard",
    nameKey: "srd:class.bard",
    hitDie: 8,
    babProgression: "three-quarters",
    saveProgressions: { fort: "poor", ref: "good", will: "good" },
    skillPointsPerLevel: 6,
    classSkillIds: [
      "acrobatics",
      "appraise",
      "bluff",
      "climb",
      "craft",
      "diplomacy",
      "disguise",
      "escapeArtist",
      "fly",
      "handleAnimal",
      "intimidate",
      ...KNOWLEDGE_ALL,
      "linguistics",
      "perception",
      "perform",
      "profession",
      "senseMotive",
      "sleightOfHand",
      "spellcraft",
      "stealth",
      "swim",
      "useMagicDevice",
    ],
    isSpellcaster: true,
    spellcastingAbility: "cha",
    features: [
      { level: 1, nameKey: "srd:classFeature.bard.bardicKnowledge" },
      { level: 1, nameKey: "srd:classFeature.bard.bardicPerformance" },
      { level: 2, nameKey: "srd:classFeature.bard.versatilePerformance" },
      { level: 3, nameKey: "srd:classFeature.bard.inspireCompetence" },
      { level: 6, nameKey: "srd:classFeature.bard.suggestion" },
      { level: 8, nameKey: "srd:classFeature.bard.dirgeOfDoom" },
      { level: 9, nameKey: "srd:classFeature.bard.inspireGreatness" },
      { level: 12, nameKey: "srd:classFeature.bard.soothingPerformance" },
      { level: 15, nameKey: "srd:classFeature.bard.inspireHeroics" },
      { level: 18, nameKey: "srd:classFeature.bard.massSuggestion" },
      { level: 20, nameKey: "srd:classFeature.bard.deadlyPerformance" },
    ],
  },
  {
    id: "cleric",
    nameKey: "srd:class.cleric",
    hitDie: 8,
    babProgression: "three-quarters",
    saveProgressions: { fort: "good", ref: "poor", will: "good" },
    skillPointsPerLevel: 2,
    classSkillIds: [
      "appraise",
      "craft",
      "diplomacy",
      "heal",
      "knowledgeArcana",
      "knowledgeHistory",
      "knowledgeNobility",
      "knowledgePlanes",
      "knowledgeReligion",
      "linguistics",
      "profession",
      "senseMotive",
      "spellcraft",
    ],
    isSpellcaster: true,
    spellcastingAbility: "wis",
    features: [
      { level: 1, nameKey: "srd:classFeature.cleric.channelEnergy" },
      { level: 1, nameKey: "srd:classFeature.cleric.domains" },
      { level: 1, nameKey: "srd:classFeature.cleric.spontaneousCasting" },
    ],
  },
  {
    id: "druid",
    nameKey: "srd:class.druid",
    hitDie: 8,
    babProgression: "three-quarters",
    saveProgressions: { fort: "good", ref: "poor", will: "good" },
    skillPointsPerLevel: 4,
    classSkillIds: [
      "climb",
      "craft",
      "fly",
      "handleAnimal",
      "heal",
      "knowledgeNature",
      "perception",
      "profession",
      "ride",
      "spellcraft",
      "survival",
      "swim",
    ],
    isSpellcaster: true,
    spellcastingAbility: "wis",
    features: [
      { level: 1, nameKey: "srd:classFeature.druid.natureBond" },
      { level: 1, nameKey: "srd:classFeature.druid.natureSense" },
      { level: 1, nameKey: "srd:classFeature.druid.wildEmpathy" },
      { level: 2, nameKey: "srd:classFeature.druid.woodlandStride" },
      { level: 3, nameKey: "srd:classFeature.druid.tracklessStep" },
      { level: 4, nameKey: "srd:classFeature.druid.resistNaturesLure" },
      { level: 4, nameKey: "srd:classFeature.druid.wildShape" },
      { level: 9, nameKey: "srd:classFeature.druid.venomImmunity" },
      { level: 13, nameKey: "srd:classFeature.druid.thousandFaces" },
      { level: 15, nameKey: "srd:classFeature.druid.timelessBody" },
    ],
  },
  {
    id: "fighter",
    nameKey: "srd:class.fighter",
    hitDie: 10,
    babProgression: "full",
    saveProgressions: { fort: "good", ref: "poor", will: "poor" },
    skillPointsPerLevel: 2,
    classSkillIds: [
      "climb",
      "craft",
      "handleAnimal",
      "intimidate",
      "knowledgeDungeoneering",
      "knowledgeEngineering",
      "profession",
      "ride",
      "survival",
      "swim",
    ],
    isSpellcaster: false,
    features: [
      { level: 1, nameKey: "srd:classFeature.fighter.bonusFeat" },
      { level: 2, nameKey: "srd:classFeature.fighter.bravery" },
      { level: 3, nameKey: "srd:classFeature.fighter.armorTraining" },
      { level: 5, nameKey: "srd:classFeature.fighter.weaponTraining" },
      { level: 19, nameKey: "srd:classFeature.fighter.armorMastery" },
      { level: 20, nameKey: "srd:classFeature.fighter.weaponMastery" },
    ],
  },
  {
    id: "monk",
    nameKey: "srd:class.monk",
    hitDie: 8,
    babProgression: "three-quarters",
    saveProgressions: { fort: "good", ref: "good", will: "good" },
    skillPointsPerLevel: 4,
    classSkillIds: [
      "acrobatics",
      "climb",
      "craft",
      "escapeArtist",
      "handleAnimal",
      "heal",
      "intimidate",
      "knowledgeHistory",
      "knowledgeReligion",
      "perception",
      "perform",
      "profession",
      "ride",
      "senseMotive",
      "stealth",
      "swim",
    ],
    isSpellcaster: false,
    features: [
      { level: 1, nameKey: "srd:classFeature.monk.flurryOfBlows" },
      { level: 1, nameKey: "srd:classFeature.monk.improvedUnarmedStrike" },
      { level: 1, nameKey: "srd:classFeature.monk.stunningFist" },
      { level: 1, nameKey: "srd:classFeature.monk.acBonus" },
      { level: 2, nameKey: "srd:classFeature.monk.evasion" },
      { level: 3, nameKey: "srd:classFeature.monk.stillMind" },
      { level: 4, nameKey: "srd:classFeature.monk.kiPool" },
      { level: 5, nameKey: "srd:classFeature.monk.purityOfBody" },
      { level: 7, nameKey: "srd:classFeature.monk.wholenessOfBody" },
      { level: 9, nameKey: "srd:classFeature.monk.improvedEvasion" },
      { level: 11, nameKey: "srd:classFeature.monk.diamondBody" },
      { level: 13, nameKey: "srd:classFeature.monk.diamondSoul" },
      { level: 15, nameKey: "srd:classFeature.monk.quiveringPalm" },
      { level: 17, nameKey: "srd:classFeature.monk.timelessBody" },
      { level: 19, nameKey: "srd:classFeature.monk.emptyBody" },
      { level: 20, nameKey: "srd:classFeature.monk.perfectSelf" },
    ],
  },
  {
    id: "paladin",
    nameKey: "srd:class.paladin",
    hitDie: 10,
    babProgression: "full",
    saveProgressions: { fort: "good", ref: "poor", will: "good" },
    skillPointsPerLevel: 2,
    classSkillIds: [
      "craft",
      "diplomacy",
      "handleAnimal",
      "heal",
      "knowledgeNobility",
      "knowledgeReligion",
      "profession",
      "ride",
      "senseMotive",
      "spellcraft",
    ],
    isSpellcaster: true,
    spellcastingAbility: "cha",
    features: [
      { level: 1, nameKey: "srd:classFeature.paladin.auraOfGood" },
      { level: 1, nameKey: "srd:classFeature.paladin.detectEvil" },
      { level: 1, nameKey: "srd:classFeature.paladin.smiteEvil" },
      { level: 2, nameKey: "srd:classFeature.paladin.divineGrace" },
      { level: 2, nameKey: "srd:classFeature.paladin.layOnHands" },
      { level: 3, nameKey: "srd:classFeature.paladin.auraOfCourage" },
      { level: 3, nameKey: "srd:classFeature.paladin.divineHealth" },
      { level: 5, nameKey: "srd:classFeature.paladin.divineBond" },
      { level: 8, nameKey: "srd:classFeature.paladin.auraOfResolve" },
      { level: 11, nameKey: "srd:classFeature.paladin.auraOfJustice" },
      { level: 14, nameKey: "srd:classFeature.paladin.auraOfFaith" },
      { level: 17, nameKey: "srd:classFeature.paladin.auraOfRighteousness" },
      { level: 20, nameKey: "srd:classFeature.paladin.holyChampion" },
    ],
  },
  {
    id: "ranger",
    nameKey: "srd:class.ranger",
    hitDie: 10,
    babProgression: "full",
    saveProgressions: { fort: "good", ref: "good", will: "poor" },
    skillPointsPerLevel: 6,
    classSkillIds: [
      "climb",
      "craft",
      "fly",
      "handleAnimal",
      "heal",
      "intimidate",
      "knowledgeDungeoneering",
      "knowledgeGeography",
      "knowledgeNature",
      "perception",
      "profession",
      "ride",
      "spellcraft",
      "stealth",
      "survival",
      "swim",
    ],
    isSpellcaster: true,
    spellcastingAbility: "wis",
    features: [
      { level: 1, nameKey: "srd:classFeature.ranger.favoredEnemy" },
      { level: 1, nameKey: "srd:classFeature.ranger.track" },
      { level: 1, nameKey: "srd:classFeature.ranger.wildEmpathy" },
      { level: 2, nameKey: "srd:classFeature.ranger.combatStyleFeat" },
      { level: 3, nameKey: "srd:classFeature.ranger.favoredTerrain" },
      { level: 4, nameKey: "srd:classFeature.ranger.huntersBond" },
      { level: 8, nameKey: "srd:classFeature.ranger.swiftTracker" },
      { level: 9, nameKey: "srd:classFeature.ranger.evasion" },
      { level: 13, nameKey: "srd:classFeature.ranger.camouflage" },
      { level: 17, nameKey: "srd:classFeature.ranger.hideInPlainSight" },
    ],
  },
  {
    id: "rogue",
    nameKey: "srd:class.rogue",
    hitDie: 8,
    babProgression: "three-quarters",
    saveProgressions: { fort: "poor", ref: "good", will: "poor" },
    skillPointsPerLevel: 8,
    classSkillIds: [
      "acrobatics",
      "appraise",
      "bluff",
      "climb",
      "craft",
      "diplomacy",
      "disableDevice",
      "disguise",
      "escapeArtist",
      "intimidate",
      "knowledgeDungeoneering",
      "knowledgeLocal",
      "linguistics",
      "perception",
      "perform",
      "profession",
      "ride",
      "senseMotive",
      "sleightOfHand",
      "stealth",
      "swim",
      "useMagicDevice",
    ],
    isSpellcaster: false,
    features: [
      { level: 1, nameKey: "srd:classFeature.rogue.sneakAttack" },
      { level: 1, nameKey: "srd:classFeature.rogue.trapfinding" },
      { level: 2, nameKey: "srd:classFeature.rogue.rogueTalent" },
      { level: 2, nameKey: "srd:classFeature.rogue.evasion" },
      { level: 3, nameKey: "srd:classFeature.rogue.trapSense" },
      { level: 4, nameKey: "srd:classFeature.rogue.uncannyDodge" },
      { level: 8, nameKey: "srd:classFeature.rogue.improvedUncannyDodge" },
      { level: 10, nameKey: "srd:classFeature.rogue.advancedTalents" },
      { level: 20, nameKey: "srd:classFeature.rogue.masterStrike" },
    ],
  },
  {
    id: "sorcerer",
    nameKey: "srd:class.sorcerer",
    hitDie: 6,
    babProgression: "half",
    saveProgressions: { fort: "poor", ref: "poor", will: "good" },
    skillPointsPerLevel: 2,
    classSkillIds: ["appraise", "bluff", "craft", "fly", "intimidate", "knowledgeArcana", "profession", "spellcraft", "useMagicDevice"],
    isSpellcaster: true,
    spellcastingAbility: "cha",
    features: [
      { level: 1, nameKey: "srd:classFeature.sorcerer.bloodline" },
      { level: 1, nameKey: "srd:classFeature.sorcerer.bloodlineArcana" },
      { level: 1, nameKey: "srd:classFeature.sorcerer.eschewMaterials" },
      { level: 7, nameKey: "srd:classFeature.sorcerer.bloodlineFeat" },
    ],
  },
  {
    id: "wizard",
    nameKey: "srd:class.wizard",
    hitDie: 6,
    babProgression: "half",
    saveProgressions: { fort: "poor", ref: "poor", will: "good" },
    skillPointsPerLevel: 2,
    classSkillIds: ["appraise", "craft", "fly", ...KNOWLEDGE_ALL, "linguistics", "profession", "spellcraft"],
    isSpellcaster: true,
    spellcastingAbility: "int",
    features: [
      { level: 1, nameKey: "srd:classFeature.wizard.arcaneBond" },
      { level: 1, nameKey: "srd:classFeature.wizard.arcaneSchool" },
      { level: 1, nameKey: "srd:classFeature.wizard.scribeScroll" },
      { level: 5, nameKey: "srd:classFeature.wizard.bonusFeat" },
      { level: 10, nameKey: "srd:classFeature.wizard.bonusFeat" },
      { level: 15, nameKey: "srd:classFeature.wizard.bonusFeat" },
      { level: 20, nameKey: "srd:classFeature.wizard.bonusFeat" },
    ],
  },
];

export const CLASSES_BY_ID: Record<string, ClassDefinition> = Object.fromEntries(CLASSES.map((c) => [c.id, c]));
