import type { SkillDefinition } from "./types";

export const SKILLS: SkillDefinition[] = [
  { id: "acrobatics", nameKey: "srd:skill.acrobatics", keyAbility: "dex", trainedOnly: false, armorCheckPenalty: true },
  { id: "appraise", nameKey: "srd:skill.appraise", keyAbility: "int", trainedOnly: false, armorCheckPenalty: false },
  { id: "bluff", nameKey: "srd:skill.bluff", keyAbility: "cha", trainedOnly: false, armorCheckPenalty: false },
  { id: "climb", nameKey: "srd:skill.climb", keyAbility: "str", trainedOnly: false, armorCheckPenalty: true },
  { id: "craft", nameKey: "srd:skill.craft", keyAbility: "int", trainedOnly: false, armorCheckPenalty: false },
  { id: "diplomacy", nameKey: "srd:skill.diplomacy", keyAbility: "cha", trainedOnly: false, armorCheckPenalty: false },
  {
    id: "disableDevice",
    nameKey: "srd:skill.disableDevice",
    keyAbility: "dex",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  { id: "disguise", nameKey: "srd:skill.disguise", keyAbility: "cha", trainedOnly: false, armorCheckPenalty: false },
  {
    id: "escapeArtist",
    nameKey: "srd:skill.escapeArtist",
    keyAbility: "dex",
    trainedOnly: false,
    armorCheckPenalty: true,
  },
  { id: "fly", nameKey: "srd:skill.fly", keyAbility: "dex", trainedOnly: false, armorCheckPenalty: true },
  {
    id: "handleAnimal",
    nameKey: "srd:skill.handleAnimal",
    keyAbility: "cha",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  { id: "heal", nameKey: "srd:skill.heal", keyAbility: "wis", trainedOnly: false, armorCheckPenalty: false },
  { id: "intimidate", nameKey: "srd:skill.intimidate", keyAbility: "cha", trainedOnly: false, armorCheckPenalty: false },
  {
    id: "knowledgeArcana",
    nameKey: "srd:skill.knowledgeArcana",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeDungeoneering",
    nameKey: "srd:skill.knowledgeDungeoneering",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeEngineering",
    nameKey: "srd:skill.knowledgeEngineering",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeGeography",
    nameKey: "srd:skill.knowledgeGeography",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeHistory",
    nameKey: "srd:skill.knowledgeHistory",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeLocal",
    nameKey: "srd:skill.knowledgeLocal",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeNature",
    nameKey: "srd:skill.knowledgeNature",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeNobility",
    nameKey: "srd:skill.knowledgeNobility",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgePlanes",
    nameKey: "srd:skill.knowledgePlanes",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "knowledgeReligion",
    nameKey: "srd:skill.knowledgeReligion",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  {
    id: "linguistics",
    nameKey: "srd:skill.linguistics",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  { id: "perception", nameKey: "srd:skill.perception", keyAbility: "wis", trainedOnly: false, armorCheckPenalty: false },
  { id: "perform", nameKey: "srd:skill.perform", keyAbility: "cha", trainedOnly: false, armorCheckPenalty: false },
  { id: "profession", nameKey: "srd:skill.profession", keyAbility: "wis", trainedOnly: true, armorCheckPenalty: false },
  { id: "ride", nameKey: "srd:skill.ride", keyAbility: "dex", trainedOnly: false, armorCheckPenalty: true },
  {
    id: "senseMotive",
    nameKey: "srd:skill.senseMotive",
    keyAbility: "wis",
    trainedOnly: false,
    armorCheckPenalty: false,
  },
  {
    id: "sleightOfHand",
    nameKey: "srd:skill.sleightOfHand",
    keyAbility: "dex",
    trainedOnly: true,
    armorCheckPenalty: true,
  },
  {
    id: "spellcraft",
    nameKey: "srd:skill.spellcraft",
    keyAbility: "int",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
  { id: "stealth", nameKey: "srd:skill.stealth", keyAbility: "dex", trainedOnly: false, armorCheckPenalty: true },
  { id: "survival", nameKey: "srd:skill.survival", keyAbility: "wis", trainedOnly: false, armorCheckPenalty: false },
  { id: "swim", nameKey: "srd:skill.swim", keyAbility: "str", trainedOnly: false, armorCheckPenalty: true },
  {
    id: "useMagicDevice",
    nameKey: "srd:skill.useMagicDevice",
    keyAbility: "cha",
    trainedOnly: true,
    armorCheckPenalty: false,
  },
];

export const SKILLS_BY_ID: Record<string, SkillDefinition> = Object.fromEntries(
  SKILLS.map((skill) => [skill.id, skill]),
);
